### ISSUE TITLE
Complete construction steps（求linux完整搭建过程，centos版本）

### ISSUE THREAD

**Issue by SIZzzzzzzz** [Melledy/Grasscutter#2018]
Complete construction steps（求linux完整搭建过程，centos版本）
If yes, please send it to the mailbox（如果有请发送到邮箱）
[1773232143@qq.com](mailto:1773232143@qq.com)
Thank you.

Maybe we can discuss it here

**Comment by SIZzzzzzzz** [comment]
Windows 10  it's fine too     win10也可以

**Comment by SIZzzzzzzz** [comment]
Server building process

**Comment by kilosonc** [comment]
我这边自己搞了个镜像
你在centos上装个docker&docker-compose，试一试这个
docker-compose -f docker-compose.yaml up -d
```
version: '3'
services:
  grasscutter:
    image: closetool/grasscutter:v1.4.3
    restart: always
    network_mode: "host"
    depends_on:
      - db
  db:
    image: mongo:6.0.3
    restart: always
    network_mode: "host"
    volumes:
      - ~/grasscutter:/data/db
```
